## Project Title: Car Resale Prices Data Cleaning & Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("car_resale_prices.csv")

In [3]:
df.columns

Index(['Column1', 'full_name', 'resale_price', 'registered_year',
       'engine_capacity', 'insurance', 'transmission_type', 'kms_driven',
       'owner_type', 'fuel_type', 'max_power', 'seats', 'mileage', 'body_type',
       'city'],
      dtype='object')

In [4]:
df.columns=df.columns.str.strip().str.lower()

In [5]:
df.columns

Index(['column1', 'full_name', 'resale_price', 'registered_year',
       'engine_capacity', 'insurance', 'transmission_type', 'kms_driven',
       'owner_type', 'fuel_type', 'max_power', 'seats', 'mileage', 'body_type',
       'city'],
      dtype='object')

In [6]:
print('number of columns:',df.shape[1])
print("number of rows:",df.shape[0])

number of columns: 15
number of rows: 17446

In [7]:
df.head(1)

,column1,full_name,resale_price,registered_year,engine_capacity,insurance,transmission_type,kms_driven,owner_type,fuel_type,max_power,seats,mileage,body_type,city
0,0,2017 Maruti Baleno 1.2 Alpha,₹ 5.45 Lakh,2017,1197 cc,Third Party insurance,Manual,"40,000 Kms",First Owner,Petrol,83.1bhp,5.0,21.4 kmpl,Hatchback,Agra

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17446 entries, 0 to 17445
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   column1            17446 non-null  int64
 1   full_name          17446 non-null  object
 2   resale_price       17446 non-null  object
 3   registered_year    17377 non-null  object
 4   engine_capacity    17432 non-null  object
 5   insurance          17439 non-null  object
 6   transmission_type  17446 non-null  object
 7   kms_driven         17443 non-null  object
 8   owner_type         17401 non-null  object
 9   fuel_type          17446 non-null  object
 10  max_power          17344 non-null  object
 11  seats              17436 non-null  float64
 12  mileage            16938 non-null  object
 13  body_type          17446 non-null  object
 14  city               17446 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 2.0+ MB

## Handiling null values.

In [9]:
# check how many null values present in our dataset.
df.isnull().sum()

column1                0
full_name              0
resale_price           0
registered_year       69
engine_capacity       14
insurance              7
transmission_type      0
kms_driven             3
owner_type            45
fuel_type              0
max_power            102
seats                 10
mileage              508
body_type              0
city                   0
dtype: int64

In [10]:
df["registered_year"]=df["registered_year"].ffill()

In [11]:
df["engine_capacity"]=df["engine_capacity"].fillna("Not available")

In [12]:
df=df.dropna(subset=["insurance"])

In [13]:
df=df.dropna(subset=["kms_driven"])

In [14]:
df["owner_type"]=df["owner_type"].fillna("Not available")

In [15]:
df["max_power"]=df["max_power"].ffill()

In [16]:
df["mileage"]=df["mileage"].ffill()

In [17]:
df=df.dropna(subset=["seats"])

In [18]:
df.isnull().sum()

column1              0
full_name            0
resale_price         0
registered_year      0
engine_capacity      0
insurance            0
transmission_type    0
kms_driven           0
owner_type           0
fuel_type            0
max_power            0
seats                0
mileage              0
body_type            0
city                 0
dtype: int64

## fixing incosistent formating

In [19]:
df.dtypes

column1                int64
full_name             object
resale_price          object
registered_year       object
engine_capacity       object
insurance             object
transmission_type     object
kms_driven            object
owner_type            object
fuel_type             object
max_power             object
seats                float64
mileage               object
body_type             object
city                  object
dtype: object

## 1.resale_price column.

In [20]:
# we remove rupeeya symbol and convert lakh or crore into hundred.
x=df["resale_price"]
def convert_amount(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()

    x = x.replace("₹","").replace(",","")

    if "Lakh" in x:
        return float(x.replace("Lakh","").strip()) * 100000

    elif "Crore" in x:
        return float(x.replace("Crore","").strip()) * 10000000

    else:
        return np.nan
df["resale_price"]=df["resale_price"].apply(convert_amount)

In [21]:
df.head(1)

,column1,full_name,resale_price,registered_year,engine_capacity,insurance,transmission_type,kms_driven,owner_type,fuel_type,max_power,seats,mileage,body_type,city
0,0,2017 Maruti Baleno 1.2 Alpha,545000.0,2017,1197 cc,Third Party insurance,Manual,"40,000 Kms",First Owner,Petrol,83.1bhp,5.0,21.4 kmpl,Hatchback,Agra

## 2.full_name column.

In [22]:
# extract year from the full_name column.
x=df["full_name"]
def ext_year(x):
    y=x.split(" ")
    return y[0]
df["registered_year"]=df["full_name"].apply(ext_year)

In [23]:
# extract car_name from the full_name column
x=df["full_name"]
def ext_car_name(x):
   y=x.split(" ")
   return " ".join(y[2:5])
df["car_name"]=df["full_name"].apply(ext_car_name)

In [24]:
df["car_name"].head(10)

0       Baleno 1.2 Alpha
1               Hexa XTA
2        Swift Dzire VXI
3        Swift Dzire VXI
4          i10 Magna 1.1
5         i20 Active 1.2
6    Tiago 1.05 Revotorq
7          i10 Magna 1.1
8          Eeco 7 Seater
9         Santro Xing GL
Name: car_name, dtype: object

In [25]:
# extract company_name from the full_name column.
x=df["full_name"]
def company_name(x):
      y=x.split(" ")
      return y[1]

df["full_name"]=df["full_name"].apply(company_name)
df.rename(columns={"full_name": "company_name"}, inplace=True)

## 3. kms_driven column.

In [26]:
x=df["kms_driven"]
def ext_numbers(x):
    return x.replace(" Kms","").replace(",","").strip()
df["kms_driven"]=df["kms_driven"].apply(ext_numbers)

In [27]:
df["kms_driven"].head(10)

0     40000
1     70000
2     70000
3     70000
4     80000
5     70000
6    120000
7     60000
8     20000
9     30000
Name: kms_driven, dtype: object

## 4.Mileage column

In [28]:
x=df["mileage"]
def remove_kmpl(x):
     return x.replace("kmpl","").replace("km/kg","").strip()
df["mileage"]=df["mileage"].apply(remove_kmpl)

## 5.engine_capacity column.

In [29]:
# we remove "0 cc" in the engine_capactiy column.because 0cc engine capacity is not available.
df = df[df["engine_capacity"].astype(str) != "0 cc"]

In [30]:
# we remove "Not available" values from the engine_capacity.
df=df[df["engine_capacity"].astype(str) != "Not available"]

In [31]:
# we remove "cc" from the engine_column.
df.loc[:, "engine_capacity"] = (
    df["engine_capacity"]
    .str.replace("cc", "", regex=False)
    .str.strip()
)

In [32]:
df["engine_capacity"].head(3)

0    1197
1    2179
2    1197
Name: engine_capacity, dtype: object

## 6.Insurance column

In [33]:
df=df[df["insurance"].astype(str) !="1"]
df=df[df["insurance"].astype(str) != "2"]
df=df[df["insurance"].astype(str) != "Not Available"]

In [34]:
x=df["insurance"]
def change_third_p(x):
    return x.replace("Third Party insurance","Third Party").strip()
df["insurance"]=df["insurance"].apply(change_third_p)

In [35]:
df["insurance"].head(10)

0    Third Party
1    Third Party
2    Third Party
3    Third Party
4    Third Party
5    Third Party
6    Third Party
7    Third Party
8    Third Party
9    Third Party
Name: insurance, dtype: object

## 7.owner type column

In [36]:
df=df[df["owner_type"].astype(str) != "Not available"]

## Changing Datatype

In [37]:
# kms_driven column datatype "object" change into "int64"
df["kms_driven"]=df["kms_driven"].astype("int64")

In [38]:
# registered_year column datatype is "object" change into "int64".
df["registered_year"]=df["registered_year"].astype("int64")

In [39]:
# Seats column datatype is "floats" change into "int64".
df["seats"]=df["seats"].astype("int64")

In [40]:
# mileage column datatype is "object" changed into "int64".
df["mileage"]=df["mileage"].astype(float)

In [41]:
# engine_capacity column datatype is "object"  changed into "int64'.
df["engine_capacity"]=df["engine_capacity"].astype("int64")

In [42]:
df.dtypes

column1                int64
company_name          object
resale_price         float64
registered_year        int64
engine_capacity        int64
insurance             object
transmission_type     object
kms_driven             int64
owner_type            object
fuel_type             object
max_power             object
seats                  int64
mileage              float64
body_type             object
city                  object
car_name              object
dtype: object

In [45]:
df["resale_price"]=df["resale_price"].fillna(df["resale_price"].median())

In [46]:
df.isnull().sum()

column1              0
company_name         0
resale_price         0
registered_year      0
engine_capacity      0
insurance            0
transmission_type    0
kms_driven           0
owner_type           0
fuel_type            0
max_power            0
seats                0
mileage              0
body_type            0
city                 0
car_name             0
dtype: int64

In [47]:
df.drop("column1",axis=1,inplace=True)

In [52]:
# Here we can clearly see 215 rows are duplicated so thats why we delet it.
df.duplicated().value_counts()

False    16451
True       215
Name: count, dtype: int64

In [55]:
df=df.drop_duplicates()

In [57]:
# Finally we delet the duplicates rows.
df.duplicated().value_counts()

False    16451
Name: count, dtype: int64

In [58]:
# we save cleaned data in the file.
df.to_csv("cleaned_car_resale_prices_data.csv",index=False)

## 🧾 Final Project Conclusion (Car Resale Dataset)

## Conclusion:

## In this project, a raw Car Resale Prices dataset was thoroughly cleaned, standardized, and transformed into an analysis-ready format.
## The major challenges included handling missing values in price-related columns, correcting inconsistent text formats, converting date columns into proper datetime format, and assigning appropriate data types.

## After preprocessing, the dataset became reliable and suitable for analytical reporting and dashboard development in Power BI.
## This project demonstrates practical expertise in data cleaning, preprocessing, and feature engineering, which are essential skills for a Data ## Analyst.